# vim: set filetype=yaml.ansible:
---
- name: "Ensure scorify user"
  become: true
  ansible.builtin.user:
    name: "scorify"
    system: true
    password_lock: true
    create_home: true
    home: "/var/lib/scorify"
    shell: "/usr/bin/nologin"
    state: "present"

- name: "Ensure scorify directory"
  become: true
  ansible.builtin.file:
    path: "/var/lib/scorify"
    state: "directory"
    owner: "scorify"
    mode: "0700"

- name: "Ensure scorify binary"
  become: true
  ansible.builtin.copy:
    src: "scorify"
    dest: "/var/lib/scorify/scorify"
    owner: "scorify"
    mode: "0700"

- name: "Ensure .env file"
  become: true
  ansible.builtin.copy:
    src: "env"
    dest: "/var/lib/scorify/.env"
    owner: "scorify"
    mode: "0600"

- name: "Ensure KotH minion systemd service"
  become: true
  notify:
    - "Reload systemd"
  ansible.builtin.template:
    src: "koth-minion.service.j2"
    dest: "/etc/systemd/system/koth-minion.service"
    mode: "0644"

- name: "Reload systemd"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: "Start & enable KotH minion systemd service"
  become: true
  ansible.builtin.systemd_service:
    name: "koth-minion.service"
    state: "started"
    enabled: true
